import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createCampaignHandler,dynamoStore,day,range} from '../scripts/release/campaign-handler.mjs';
class GetCommand{constructor(input){this.input=input;}}
class QueryCommand extends GetCommand{}
class UpdateCommand extends GetCommand{}
class TransactWriteCommand extends GetCommand{}
function fakeDynamo(){
 const rows=new Map();const key=o=>o.pk+'|'+o.sk;
 const cancelled=()=>Object.assign(Error('Conditional failure'),{name:'TransactionCanceledException'});
 const client={async send(command){const i=command.input;
  if(command instanceof TransactWriteCommand){
   for(const op of i.TransactItems){const w=op.Put||op.Update;const item=w.Item||w.Key;const old=rows.get(key(item));if(w.ConditionExpression==='attribute_not_exists(pk)'&&old)throw cancelled();if(w.ConditionExpression==='attribute_exists(pk)'&&!old)throw cancelled();if(w.ConditionExpression==='lastSeen = :old'&&old?.lastSeen!==w.ExpressionAttributeValues[':old'])throw cancelled();}
   for(const op of i.TransactItems){if(op.Put)rows.set(key(op.Put.Item),structuredClone(op.Put.Item));else rows.get(key(op.Update.Key)).status=op.Update.ExpressionAttributeValues[':s'];}return {};
  }
  if(command instanceof QueryCommand){const v=i.ExpressionAttributeValues;if(v[':a']==='')throw Error('Empty key boundary');return {Items:[...rows.values()].filter(r=>r.pk===v[':p']&&r.sk>=v[':a']&&r.sk<=v[':b']).map(r=>structuredClone(r))};}
  if(command instanceof UpdateCommand){const k=key(i.Key),v=i.ExpressionAttributeValues;const old=rows.get(k)||{...i.Key,total:0,excluded:0};rows.set(k,{...old,total:old.total+v[':one'],excluded:old.excluded+v[':x'],expires:v[':e']});return {};}
  return {Item:structuredClone(rows.get(key(i.Key)))};
 }};
 return {rows,sdk:{DynamoDBClient:class{},DynamoDBDocumentClient:{from:()=>client},GetCommand,QueryCommand,UpdateCommand,TransactWriteCommand}};
}
const origin='https://proairesis.digital';
const http=(method,path,body,headers={})=>({requestContext:{http:{method}},rawPath:path,headers:{origin,'user-agent':'Mozilla/5.0',...headers},body:JSON.stringify(body)});
async function fixture(){const fake=fakeDynamo();const store=await dynamoStore('test',fake.sdk);let now=Date.parse('2026-09-14T03:00:00Z');const handler=createCampaignHandler({store,origin,clock:()=>now});await handler({adminAction:'create',slug:'linkedin-launch-202609',name:'Launch',destination:'/',actor:'test'});return {store,handler,rows:fake.rows,setTime:n=>now=n,now};}
test('IAM management creates campaigns; HTTP cannot invoke admin commands',async()=>{const f=await fixture();const reply=await f.handler({...http('POST','/api/campaigns/admin',{adminAction:'report'}),adminAction:'report'});assert.equal(reply.statusCode,404);const r=await f.handler({adminAction:'report'});assert.equal(r.campaigns.length,1);assert.equal(r.campaigns[0].visits,0);});
test('redirects preserve attribution; previews and test links count only as raw excluded requests',async()=>{const f=await fixture();const e=http('GET','/r/linkedin-launch-202609',null,{'user-agent':'LinkedInBot'});let r=await f.handler(e);assert.equal(r.statusCode,302);assert.equal(new URL(r.headers.location).origin,origin);assert.equal(new URL(r.headers.location).searchParams.get('utm_source'),'linkedin');r=await f.handler({...e,headers:{'user-agent':'Mozilla'},queryStringParameters:{rc_test:'1'}});assert.equal(new URL(r.headers.location).searchParams.get('rc_test'),'1');const report=await f.handler({adminAction:'report'});assert.equal(report.campaigns[0].requests,2);assert.equal(report.campaigns[0].excluded,2);assert.equal(report.campaigns[0].visits,0);});
test('only valid consented same-origin visits are accepted',async()=>{const f=await fixture();const body={campaign:'linkedin-launch-202609',visitor:randomUUID(),event:randomUUID(),consent:true};assert.equal((await f.handler(http('POST','/api/campaigns/visit',body,{origin:'https://evil.example'}))).statusCode,403);assert.equal((await f.handler(http('POST','/api/campaigns/visit',{...body,consent:false}))).statusCode,400);assert.equal((await f.handler(http('POST','/api/campaigns/visit',{...body,event:'invalid'}))).statusCode,400);assert.equal((await f.handler(http('POST','/api/campaigns/visit',{...body,test:true}))).statusCode,204);assert.equal((await f.handler({adminAction:'report'})).campaigns[0].visits,0);});
test('retries, separate tabs, 30-minute inactivity and range-wide unique browsers',async()=>{const f=await fixture(),visitor=randomUUID(),event=randomUUID();const send=async(v,e)=>f.handler(http('POST','/api/campaigns/visit',{campaign:'linkedin-launch-202609',visitor:v,event:e,consent:true}));await send(visitor,event);await send(visitor,event);await send(visitor,randomUUID());await send(randomUUID(),randomUUID());let r=await f.handler({adminAction:'report'});assert.equal(r.campaigns[0].visits,2);assert.equal(r.campaigns[0].visitors,2);f.setTime(f.now+1800000);await send(visitor,randomUUID());r=await f.handler({adminAction:'report'});assert.equal(r.campaigns[0].visits,3);assert.equal(r.campaigns[0].visitors,2);f.setTime(f.now+86400000);await send(visitor,randomUUID());r=await f.handler({adminAction:'report'});assert.equal(r.campaigns[0].visits,4);assert.equal(r.campaigns[0].visitors,2);assert.equal(r.daily.length,2);assert.ok([...f.rows.values()].filter(r=>r.pk.startsWith('C#')).every(r=>typeof r.expires==='number'));});
test('invalid slugs, duplicate campaigns and arbitrary destinations are rejected',async()=>{const f=await fixture();assert.equal((await f.handler(http('GET','/r/no-such-link'))).statusCode,404);assert.equal((await f.handler(http('GET','/r/../../admin'))).statusCode,404);assert.match((await f.handler({adminAction:'create',slug:'bad-link',name:'X',destination:'https://evil.example'})).error,/approved/);assert.match((await f.handler({adminAction:'create',slug:'linkedin-launch-202609',name:'X',destination:'/'})).error,/already/);});
test('archived links still resolve and report',async()=>{const f=await fixture();await f.handler({adminAction:'archive',slug:'linkedin-launch-202609'});assert.equal((await f.handler(http('GET','/r/linkedin-launch-202609'))).statusCode,302);assert.equal((await f.handler({adminAction:'report'})).campaigns[0].status,'archived');});
test('Sydney calendar boundaries and invalid report dates',()=>{const now=Date.parse('2026-10-04T13:30:00Z');assert.equal(day(now),'2026-10-05');assert.equal(day(Date.parse('2026-09-14T14:30:00Z')),'2026-09-15');assert.throws(()=>range('2026-02-30','2026-03-01',now));assert.throws(()=>range('2020-01-01','2026-10-05',now));assert.throws(()=>range('2026-10-05','2026-10-04',now));});
test('collector failures preserve navigation and do not disclose internals',async()=>{const handler=createCampaignHandler({origin,store:{find:async()=>{throw Error('private connection data');}}});const r=await handler(http('GET','/r/linkedin-launch-202609'));assert.equal(r.statusCode,302);assert.equal(r.headers.location,origin+'/');assert.ok(!r.body.includes('private'));});
