import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {safePath,draft,writeManifest,verify,materialize,routes} from '../scripts/release/bundle.mjs';
test('reject traversal, ambiguous paths and draft content',()=>{for(const p of ['../secret','/absolute','a/../b','a\\b','a//b'])assert.throws(()=>safePath(p));assert.equal(draft('[INSERT PROVIDER]'),true);assert.equal(draft('Working draft'),true);assert.equal(draft('Current website terms'),false);});
test('integrity detects tampered and additional files',async()=>{const d=await mkdtemp(path.join(tmpdir(),'release-test-'));try{await writeFile(path.join(d,'index.html'),'original');await writeManifest(d,{kind:'bundle',routes});await verify(d);await writeFile(path.join(d,'index.html'),'changed');await assert.rejects(verify(d),/integrity/);await writeFile(path.join(d,'index.html'),'original');await mkdir(path.join(d,'extra'));await writeFile(path.join(d,'extra/manifest.json'),'unexpected');await assert.rejects(verify(d),/integrity/);}finally{await rm(d,{recursive:true,force:true});}});
test('promotion preserves the bundle identity and rejects a different staging digest',async()=>{const d=await mkdtemp(path.join(tmpdir(),'promotion-test-'));try{const b=path.join(d,'bundle');await mkdir(b);for(const route of routes){const f=path.join(b,route==='/'?'index.html':route.slice(1)+'/index.html');await mkdir(path.dirname(f),{recursive:true});await writeFile(f,'<html>__SITE_ORIGIN__ __ROBOTS__ __ENVIRONMENT__</html>');}const m=await writeManifest(b,{kind:'bundle',routes,source:'test'});const stage=await materialize(b,path.join(d,'stage'),'staging');const prod=await materialize(b,path.join(d,'prod'),'production',stage.bundleDigest);assert.equal(prod.bundleDigest,m.digest);await assert.rejects(materialize(b,path.join(d,'bad'),'production','different'),/match staging/);assert.equal((await verify(b)).digest,m.digest);}finally{await rm(d,{recursive:true,force:true});}});
