import type { AdminIdentity, AdminSnapshot } from './admin-types';

export const demoAdmin: AdminIdentity = {
  id: 'admin_demo',
  name: 'Jenny Men',
  email: 'seedy@sites.test',
  initials: 'JM',
};

export const demoSnapshot: AdminSnapshot = {
  totals: {
    b2cUsers: 1248,
    activeB2cUsers: 1184,
    activeConsultants: 24,
    pendingConsultants: 3,
    unassignedUsers: 17,
    deliverySuccessRate: 96.8,
    crmLeads: 186,
    crmActivePipeline: 742,
    crmFollowUpsDue: 9,
    commissionActionable: 2,
  },
  users: [
    {
      id: 'PIP-10482',
      name: 'Maya Chen',
      email: 'maya.chen@example.com',
      initials: 'MC',
      role: 'registered_user',
      status: 'active',
      onboarding: 'Complete',
      consultant: 'Amelia Hart',
      lastActive: '8 min ago',
      createdAt: '6 Sep 2026',
      emailVerified: true,
    },
    {
      id: 'PIP-10481',
      name: 'Noah Williams',
      email: 'noah.w@example.com',
      initials: 'NW',
      role: 'registered_user',
      status: 'active',
      onboarding: 'Profile review',
      consultant: 'Unassigned',
      lastActive: '34 min ago',
      createdAt: '6 Sep 2026',
      emailVerified: true,
    },
    {
      id: 'PIP-10480',
      name: 'Priya Nair',
      email: 'priya.nair@example.com',
      initials: 'PN',
      role: 'registered_user',
      status: 'invited',
      onboarding: 'Not started',
      consultant: 'Unassigned',
      lastActive: 'Never',
      createdAt: '5 Sep 2026',
      emailVerified: false,
    },
    {
      id: 'PIP-10479',
      name: 'Liam Foster',
      email: 'liam.foster@example.com',
      initials: 'LF',
      role: 'registered_user',
      status: 'suspended',
      onboarding: 'Complete',
      consultant: 'Theo Grant',
      lastActive: '2 days ago',
      createdAt: '3 Sep 2026',
      emailVerified: true,
    },
    {
      id: 'PIP-10478',
      name: 'Sofia Alvarez',
      email: 'sofia.a@example.com',
      initials: 'SA',
      role: 'registered_user',
      status: 'active',
      onboarding: 'Complete',
      consultant: 'Amelia Hart',
      lastActive: '4 hours ago',
      createdAt: '2 Sep 2026',
      emailVerified: true,
    },
  ],
  consultants: [
    {
      userId: 'PIP-C019',
      name: 'Jordan Lee',
      email: 'jordan.lee@example.com',
      initials: 'JL',
      speciality: 'Technology careers',
      submitted: 'Today, 9:42 am',
      checksCompleted: 4,
      checksRequired: 5,
      applicationStatus: 'submitted',
      accountStatus: 'invited',
      activeAssignments: 0,
    },
    {
      userId: 'PIP-C018',
      name: 'Sienna Brooks',
      email: 'sienna.b@example.com',
      initials: 'SB',
      speciality: 'Graduate pathways',
      submitted: 'Yesterday',
      checksCompleted: 5,
      checksRequired: 5,
      applicationStatus: 'submitted',
      accountStatus: 'invited',
      activeAssignments: 0,
    },
    {
      userId: 'PIP-C017',
      name: 'Daniel Okafor',
      email: 'daniel.o@example.com',
      initials: 'DO',
      speciality: 'Migrant professionals',
      submitted: '4 Sep 2026',
      checksCompleted: 3,
      checksRequired: 5,
      applicationStatus: 'more_information_required',
      accountStatus: 'invited',
      activeAssignments: 0,
    },
    {
      userId: 'PIP-C011',
      name: 'Amelia Hart',
      email: 'amelia.h@example.com',
      initials: 'AH',
      speciality: 'Technology careers',
      submitted: '22 Aug 2026',
      checksCompleted: 5,
      checksRequired: 5,
      applicationStatus: 'approved',
      accountStatus: 'active',
      activeAssignments: 18,
    },
    {
      userId: 'PIP-C006',
      name: 'Theo Grant',
      email: 'theo.g@example.com',
      initials: 'TG',
      speciality: 'Career transitions',
      submitted: '11 Aug 2026',
      checksCompleted: 5,
      checksRequired: 5,
      applicationStatus: 'approved',
      accountStatus: 'active',
      activeAssignments: 12,
    },
  ],
  assignments: [
    {
      id: 'ASN-2031',
      candidateId: 'PIP-10482',
      candidateName: 'Maya Chen',
      consultantId: 'PIP-C011',
      consultantName: 'Amelia Hart',
      consentScope: 'Career coaching and application review',
      consentedAt: '1 Sep 2026',
      createdAt: '1 Sep 2026',
      status: 'active',
    },
    {
      id: 'ASN-2028',
      candidateId: 'PIP-10479',
      candidateName: 'Liam Foster',
      consultantId: 'PIP-C006',
      consultantName: 'Theo Grant',
      consentScope: 'Career coaching',
      consentedAt: '29 Aug 2026',
      createdAt: '29 Aug 2026',
      status: 'active',
    },
    {
      id: 'ASN-2023',
      candidateId: 'PIP-10478',
      candidateName: 'Sofia Alvarez',
      consultantId: 'PIP-C011',
      consultantName: 'Amelia Hart',
      consentScope: 'Application review',
      consentedAt: '26 Aug 2026',
      createdAt: '26 Aug 2026',
      status: 'active',
    },
  ],
  workflowRuns: [
    {
      id: 'RUN-8832',
      userName: 'Maya Chen',
      workflowType: 'Shortlist delivery',
      status: 'succeeded',
      summary: '4 evidence-backed roles delivered',
      createdAt: 'Today, 10:32 am',
    },
    {
      id: 'RUN-8831',
      userName: 'Noah Williams',
      workflowType: 'Eligibility review',
      status: 'partial',
      summary: '2 roles need human review',
      createdAt: 'Today, 10:29 am',
    },
    {
      id: 'RUN-8830',
      userName: 'Sofia Alvarez',
      workflowType: 'Job discovery',
      status: 'failed',
      summary: 'One source was temporarily unavailable',
      createdAt: 'Today, 10:20 am',
    },
    {
      id: 'RUN-8829',
      userName: 'Maya Chen',
      workflowType: 'Application pack',
      status: 'succeeded',
      summary: 'Draft ready for candidate review',
      createdAt: 'Yesterday, 4:14 pm',
    },
  ],
  auditEvents: [
    {
      id: 481,
      actorEmail: 'admin@pip.example',
      action: 'consultant.application_approved',
      targetType: 'consultant',
      targetId: 'PIP-C011',
      reason: 'All professional checks completed',
      outcome: 'succeeded',
      createdAt: '22 Aug 2026, 2:12 pm',
    },
    {
      id: 480,
      actorEmail: 'admin@pip.example',
      action: 'assignment.created',
      targetType: 'candidate',
      targetId: 'PIP-10482',
      reason: 'Candidate consent recorded',
      outcome: 'succeeded',
      createdAt: '1 Sep 2026, 9:08 am',
    },
    {
      id: 479,
      actorEmail: 'admin@pip.example',
      action: 'user.suspended',
      targetType: 'user',
      targetId: 'PIP-10479',
      reason: 'Support review requested',
      outcome: 'succeeded',
      createdAt: '4 Sep 2026, 11:31 am',
    },
  ],
  crmContacts: [
    {
      userId: 'PIP-10482',
      name: 'Maya Chen',
      email: 'maya.chen@example.com',
      initials: 'MC',
      contactType: 'B2C candidate',
      accountStatus: 'active',
      stage: 'active_search',
      priority: 'high',
      ownerName: 'Jenny Men',
      source: 'Organic search',
      tags: ['Data', 'Sydney'],
      nextAction: 'Review shortlist feedback',
      nextFollowUpAt: 'Today, 3:00 pm',
      nextFollowUpAtIso: '2026-09-06T15:00:00.000Z',
      lastContactedAt: '2 hours ago',
    },
    {
      userId: 'PIP-10481',
      name: 'Noah Williams',
      email: 'noah.w@example.com',
      initials: 'NW',
      contactType: 'B2C candidate',
      accountStatus: 'active',
      stage: 'onboarding',
      priority: 'normal',
      ownerName: 'Jenny Men',
      source: 'Founder referral',
      tags: ['Graduate'],
      nextAction: 'Complete profile review',
      nextFollowUpAt: 'Tomorrow, 10:30 am',
      nextFollowUpAtIso: '2026-09-07T10:30:00.000Z',
      lastContactedAt: 'Yesterday',
    },
    {
      userId: 'PIP-10480',
      name: 'Priya Nair',
      email: 'priya.nair@example.com',
      initials: 'PN',
      contactType: 'B2C candidate',
      accountStatus: 'invited',
      stage: 'lead',
      priority: 'normal',
      ownerName: 'Unassigned',
      source: 'Waitlist',
      tags: ['Product'],
      nextAction: 'Send welcome follow-up',
      nextFollowUpAt: '8 Sep 2026',
      nextFollowUpAtIso: '2026-09-08T09:00:00.000Z',
      lastContactedAt: 'Never',
    },
    {
      userId: 'PIP-10479',
      name: 'Liam Foster',
      email: 'liam.foster@example.com',
      initials: 'LF',
      contactType: 'B2C candidate',
      accountStatus: 'suspended',
      stage: 'nurture',
      priority: 'low',
      ownerName: 'Jenny Men',
      source: 'LinkedIn',
      tags: ['Career change'],
      nextAction: 'Check readiness next month',
      nextFollowUpAt: '1 Oct 2026',
      nextFollowUpAtIso: '2026-10-01T09:00:00.000Z',
      lastContactedAt: '2 days ago',
    },
    {
      userId: 'PIP-10478',
      name: 'Sofia Alvarez',
      email: 'sofia.a@example.com',
      initials: 'SA',
      contactType: 'B2C candidate',
      accountStatus: 'active',
      stage: 'placed',
      priority: 'normal',
      ownerName: 'Jenny Men',
      source: 'Community event',
      tags: ['Placed', 'Marketing'],
      nextAction: 'Request placement story',
      nextFollowUpAt: '12 Sep 2026',
      nextFollowUpAtIso: '2026-09-12T11:00:00.000Z',
      lastContactedAt: '4 hours ago',
    },
  ],
  crmActivities: [
    {
      id: 'CRM-ACT-103',
      contactUserId: 'PIP-10482',
      contactName: 'Maya Chen',
      activityType: 'call',
      summary:
        'Discussed the first shortlist and clarified preferred team size.',
      actorName: 'Jenny Men',
      occurredAt: '2 hours ago',
    },
    {
      id: 'CRM-ACT-102',
      contactUserId: 'PIP-10481',
      contactName: 'Noah Williams',
      activityType: 'email',
      summary: 'Sent profile completion guidance and the evidence checklist.',
      actorName: 'Jenny Men',
      occurredAt: 'Yesterday',
    },
    {
      id: 'CRM-ACT-101',
      contactUserId: 'PIP-10478',
      contactName: 'Sofia Alvarez',
      activityType: 'meeting',
      summary:
        'Recorded placement outcome and agreed on a later success-story follow-up.',
      actorName: 'Jenny Men',
      occurredAt: '2 Sep 2026',
    },
  ],
  crmTasks: [
    {
      id: 'CRM-TASK-52',
      contactUserId: 'PIP-10482',
      contactName: 'Maya Chen',
      title: 'Review shortlist feedback',
      dueAt: 'Today, 3:00 pm',
      dueAtIso: '2026-09-06T15:00:00.000Z',
      status: 'open',
      priority: 'high',
      isDue: true,
    },
    {
      id: 'CRM-TASK-51',
      contactUserId: 'PIP-10481',
      contactName: 'Noah Williams',
      title: 'Complete profile review',
      dueAt: 'Tomorrow, 10:30 am',
      dueAtIso: '2026-09-07T10:30:00.000Z',
      status: 'open',
      priority: 'normal',
      isDue: false,
    },
  ],
  commissionStaff: [
    {
      id: 'COMM-STAFF-01',
      name: 'Amara Singh',
      email: 'amara@example.com',
      team: 'marketing',
      status: 'active',
    },
    {
      id: 'COMM-STAFF-02',
      name: 'Ben Carter',
      email: 'ben@example.com',
      team: 'field_promotion',
      status: 'active',
    },
    {
      id: 'COMM-STAFF-03',
      name: 'Olivia Park',
      email: 'olivia@example.com',
      team: 'operations',
      status: 'active',
    },
    {
      id: 'COMM-STAFF-04',
      name: 'Ethan Cole',
      email: 'ethan@example.com',
      team: 'sales',
      status: 'active',
    },
    {
      id: 'COMM-STAFF-05',
      name: 'Grace Liu',
      email: 'grace@example.com',
      team: 'sales',
      status: 'active',
    },
  ],
  commissionRules: [
    {
      sourceType: 'marketing',
      poolRatePercent: 10,
      leadSharePercent: 30,
      salesSharePercent: 70,
      holdDays: 7,
      configured: true,
    },
    {
      sourceType: 'field_promotion',
      poolRatePercent: 10,
      leadSharePercent: 40,
      salesSharePercent: 60,
      holdDays: 7,
      configured: true,
    },
    {
      sourceType: 'operations',
      poolRatePercent: 10,
      leadSharePercent: 25,
      salesSharePercent: 75,
      holdDays: 7,
      configured: true,
    },
    {
      sourceType: 'referral',
      poolRatePercent: 10,
      leadSharePercent: 35,
      salesSharePercent: 65,
      holdDays: 7,
      configured: true,
    },
  ],
  commissionEntries: [
    {
      id: 'COMM-2026-003',
      contactUserId: 'PIP-10482',
      contactName: 'Maya Chen',
      sourceType: 'marketing',
      sourceDetail: 'Spring search campaign',
      leadStaffName: 'Amara Singh',
      salesStaffName: 'Ethan Cole',
      grossAmountCents: 200000,
      currency: 'AUD',
      poolRatePercent: 10,
      leadSharePercent: 30,
      salesSharePercent: 70,
      commissionPoolCents: 20000,
      leadCommissionCents: 6000,
      salesCommissionCents: 14000,
      status: 'eligible',
      convertedAt: '28 Aug, 11:20 am',
      eligibleAt: '4 Sep, 11:20 am',
      eligibleAtIso: '2026-09-04T11:20:00.000Z',
      stripeInvoiceId: 'in_demo_maya',
      note: 'Annual membership sale.',
    },
    {
      id: 'COMM-2026-002',
      contactUserId: 'PIP-10481',
      contactName: 'Noah Williams',
      sourceType: 'referral',
      sourceDetail: 'Founder network referral',
      leadStaffName: 'Olivia Park',
      salesStaffName: 'Grace Liu',
      grossAmountCents: 150000,
      currency: 'NZD',
      poolRatePercent: 10,
      leadSharePercent: 35,
      salesSharePercent: 65,
      commissionPoolCents: 15000,
      leadCommissionCents: 5250,
      salesCommissionCents: 9750,
      status: 'pending',
      convertedAt: '4 Sep, 2:45 pm',
      eligibleAt: '11 Sep, 2:45 pm',
      eligibleAtIso: '2026-09-11T14:45:00.000Z',
      stripeInvoiceId: 'in_demo_noah',
      note: 'Pending the seven-day refund period.',
    },
    {
      id: 'COMM-2026-001',
      contactUserId: 'PIP-10478',
      contactName: 'Sofia Alvarez',
      sourceType: 'field_promotion',
      sourceDetail: 'Sydney careers event',
      leadStaffName: 'Ben Carter',
      salesStaffName: 'Ethan Cole',
      grossAmountCents: 250000,
      currency: 'AUD',
      poolRatePercent: 10,
      leadSharePercent: 40,
      salesSharePercent: 60,
      commissionPoolCents: 25000,
      leadCommissionCents: 10000,
      salesCommissionCents: 15000,
      status: 'approved',
      convertedAt: '20 Aug, 9:15 am',
      eligibleAt: '27 Aug, 9:15 am',
      eligibleAtIso: '2026-08-27T09:15:00.000Z',
      stripeInvoiceId: 'in_demo_sofia',
      note: 'Approved for the next payroll run.',
    },
  ],
};
