import type { TaskWorkspaceSnapshot } from './task-types';

const migrationSource =
  '05 Goals/Active/Skilled Migration Outcome/Workstreams/ACS Skills Assessment.md';
const roleSource = '05 Goals/Active/Next IT Role/GOAL.md';
const journalSource = '03 Agenda/Journal/2026/2026-W37.md';
const startupSource = '05 Goals/Active/AI Startup/GOAL.md';

export const demoTaskWorkspace: TaskWorkspaceSnapshot = {
  agentCapacity: 4,
  dependencies: [
    {
      id: 'dependency_acs_review_update',
      taskId: 'task_acs_update',
      dependsOnTaskId: 'task_acs_review',
      requirement: 'complete',
    },
    {
      id: 'dependency_resume_interview',
      taskId: 'task_interview_pack',
      dependsOnTaskId: 'task_canonical_resume',
      requirement: 'complete',
    },
  ],
  tasks: [
    {
      id: 'task_skills_assessment',
      title: 'ACS skills assessment outcome',
      description:
        'Track the submitted assessment and activate the post-result migration work.',
      contextType: 'personal',
      contextName: 'Skilled migration',
      parentId: null,
      workflowKey: 'skills_assessment_demo',
      workflowType: 'Skills assessment',
      status: 'waiting',
      priority: 'high',
      executorType: 'hybrid',
      accountableName: 'Jenny Men',
      waitingReason: 'Waiting for the ACS outcome',
      activationEvent: null,
      conditionText: '',
      sourceLabel: 'ACS Skills Assessment',
      sourcePath: migrationSource,
      startAt: null,
      dueAt: '2026-10-15T06:00:00.000Z',
      completedAt: null,
      updatedAt: '2026-09-09T08:10:00.000Z',
    },
    {
      id: 'task_acs_submit',
      title: 'Submit new ACS skills assessment',
      description: 'Submission is recorded in the migration goal.',
      contextType: 'personal',
      contextName: 'Skilled migration',
      parentId: 'task_skills_assessment',
      workflowKey: 'skills_assessment_demo',
      workflowType: 'Skills assessment',
      status: 'done',
      priority: 'high',
      executorType: 'human',
      accountableName: 'Jenny Men',
      waitingReason: '',
      activationEvent: null,
      conditionText: '',
      sourceLabel: 'ACS Skills Assessment',
      sourcePath: migrationSource,
      startAt: null,
      dueAt: null,
      completedAt: '2026-08-26T04:00:00.000Z',
      updatedAt: '2026-08-26T04:00:00.000Z',
    },
    {
      id: 'task_acs_wait',
      title: 'Wait for assessment outcome',
      description:
        'No routine ACS action is required while the outcome is pending.',
      contextType: 'personal',
      contextName: 'Skilled migration',
      parentId: 'task_skills_assessment',
      workflowKey: 'skills_assessment_demo',
      workflowType: 'Skills assessment',
      status: 'waiting',
      priority: 'normal',
      executorType: 'human',
      accountableName: 'Jenny Men',
      waitingReason: 'External result',
      activationEvent: null,
      conditionText: '',
      sourceLabel: 'ACS Skills Assessment',
      sourcePath: migrationSource,
      startAt: null,
      dueAt: null,
      completedAt: null,
      updatedAt: '2026-09-09T08:10:00.000Z',
    },
    {
      id: 'task_acs_review',
      title: 'Review result, occupation and validity dates',
      description:
        'Verify what the outcome changes before updating any pathway.',
      contextType: 'personal',
      contextName: 'Skilled migration',
      parentId: 'task_skills_assessment',
      workflowKey: 'skills_assessment_demo',
      workflowType: 'Skills assessment',
      status: 'planned',
      priority: 'urgent',
      executorType: 'hybrid',
      accountableName: 'Jenny Men',
      waitingReason: 'Condition not met',
      activationEvent: 'assessment_result_received',
      conditionText: 'Activates when the ACS result is received',
      sourceLabel: 'Skilled Migration Outcome',
      sourcePath: '05 Goals/Active/Skilled Migration Outcome/GOAL.md',
      startAt: null,
      dueAt: null,
      completedAt: null,
      updatedAt: '2026-09-09T08:10:00.000Z',
    },
    {
      id: 'task_acs_update',
      title: 'Update migration evidence and pathway actions',
      description:
        'Update ACT 190, partner-led 189 and role criteria as needed.',
      contextType: 'personal',
      contextName: 'Skilled migration',
      parentId: 'task_skills_assessment',
      workflowKey: 'skills_assessment_demo',
      workflowType: 'Skills assessment',
      status: 'planned',
      priority: 'high',
      executorType: 'agent',
      accountableName: 'Jenny Men',
      waitingReason: 'Condition not met',
      activationEvent: 'assessment_result_received',
      conditionText: 'Activates when the ACS result is received',
      sourceLabel: 'Skilled Migration Outcome',
      sourcePath: '05 Goals/Active/Skilled Migration Outcome/GOAL.md',
      startAt: null,
      dueAt: null,
      completedAt: null,
      updatedAt: '2026-09-09T08:10:00.000Z',
    },
    {
      id: 'task_next_role',
      title: 'Secure the next suitable IT role',
      description:
        'Run the approval-gated job search while checking migration relevance.',
      contextType: 'project',
      contextName: 'Next IT role',
      parentId: null,
      workflowKey: 'next_role_demo',
      workflowType: 'Job search',
      status: 'doing',
      priority: 'urgent',
      executorType: 'hybrid',
      accountableName: 'Jenny Men',
      waitingReason: '',
      activationEvent: null,
      conditionText: '',
      sourceLabel: 'Next IT Role goal',
      sourcePath: roleSource,
      startAt: null,
      dueAt: '2026-11-30T12:59:00.000Z',
      completedAt: null,
      updatedAt: '2026-09-09T09:15:00.000Z',
    },
    {
      id: 'task_canonical_resume',
      title: 'Finish canonical IT résumé',
      description: 'Create the reusable, evidence-backed application profile.',
      contextType: 'project',
      contextName: 'Next IT role',
      parentId: 'task_next_role',
      workflowKey: 'next_role_demo',
      workflowType: 'Job search',
      status: 'doing',
      priority: 'urgent',
      executorType: 'hybrid',
      accountableName: 'Jenny Men',
      waitingReason: '',
      activationEvent: null,
      conditionText: '',
      sourceLabel: 'Next IT Role goal',
      sourcePath: roleSource,
      startAt: null,
      dueAt: '2026-09-10T10:00:00.000Z',
      completedAt: null,
      updatedAt: '2026-09-09T09:15:00.000Z',
    },
    {
      id: 'task_reference_email',
      title: 'Ask Graham to be a referee',
      description: 'Draft with an agent, then review and send personally.',
      contextType: 'relationship',
      contextName: 'Professional references',
      parentId: 'task_next_role',
      workflowKey: 'next_role_demo',
      workflowType: 'Job search',
      status: 'ready',
      priority: 'high',
      executorType: 'hybrid',
      accountableName: 'Jenny Men',
      waitingReason: '',
      activationEvent: null,
      conditionText: '',
      sourceLabel: '2026-W37 journal',
      sourcePath: journalSource,
      startAt: null,
      dueAt: '2026-09-10T01:00:00.000Z',
      completedAt: null,
      updatedAt: '2026-09-09T09:15:00.000Z',
    },
    {
      id: 'task_interview_pack',
      title: 'Prepare interview evidence pack',
      description:
        'Collect role evidence, stories and questions for the interview.',
      contextType: 'project',
      contextName: 'Next IT role',
      parentId: 'task_next_role',
      workflowKey: 'next_role_demo',
      workflowType: 'Job application',
      status: 'planned',
      priority: 'high',
      executorType: 'agent',
      accountableName: 'Jenny Men',
      waitingReason: 'Condition not met',
      activationEvent: 'interview_received',
      conditionText: 'Activates when an interview invitation is recorded',
      sourceLabel: 'Next IT Role goal',
      sourcePath: roleSource,
      startAt: null,
      dueAt: null,
      completedAt: null,
      updatedAt: '2026-09-09T09:15:00.000Z',
    },
    {
      id: 'task_pte',
      title: 'Reach PTE four 7s',
      description: 'Complete a mock test, record scores and book the exam.',
      contextType: 'personal',
      contextName: 'English learning',
      parentId: null,
      workflowKey: 'pte_demo',
      workflowType: 'Goal',
      status: 'ready',
      priority: 'high',
      executorType: 'human',
      accountableName: 'Jenny Men',
      waitingReason: '',
      activationEvent: null,
      conditionText: '',
      sourceLabel: 'PTE Four 7s goal',
      sourcePath: '05 Goals/Active/2026-09-15 - PTE Four 7s/GOAL.md',
      startAt: null,
      dueAt: '2026-09-30T12:59:00.000Z',
      completedAt: null,
      updatedAt: '2026-09-09T07:30:00.000Z',
    },
    {
      id: 'task_customer_messages',
      title: 'Send 3–5 personalised customer messages',
      description: 'Record each message in the Proairesis AI sales pipeline.',
      contextType: 'company',
      contextName: 'Proairesis AI',
      parentId: null,
      workflowKey: 'startup_demo',
      workflowType: 'Customer validation',
      status: 'ready',
      priority: 'high',
      executorType: 'human',
      accountableName: 'Jenny Men',
      waitingReason: '',
      activationEvent: null,
      conditionText: '',
      sourceLabel: '2026-W37 journal',
      sourcePath: journalSource,
      startAt: null,
      dueAt: '2026-09-09T12:00:00.000Z',
      completedAt: null,
      updatedAt: '2026-09-09T07:30:00.000Z',
    },
    {
      id: 'task_agent_group',
      title: 'Pilot an Agent Group on real daily work',
      description:
        'Define responsibilities, permissions, hand-offs, reporting and human review.',
      contextType: 'project',
      contextName: 'Personal operations',
      parentId: null,
      workflowKey: 'agent_group_demo',
      workflowType: 'Agent operations',
      status: 'doing',
      priority: 'normal',
      executorType: 'hybrid',
      accountableName: 'Jenny Men',
      waitingReason: '',
      activationEvent: null,
      conditionText: '',
      sourceLabel: '2026-W37 journal',
      sourcePath: journalSource,
      startAt: null,
      dueAt: '2026-09-13T12:59:00.000Z',
      completedAt: null,
      updatedAt: '2026-09-09T09:45:00.000Z',
    },
    {
      id: 'task_business_sot',
      title: 'Draft one-page Business Source of Truth',
      description: 'Choose one reachable segment and schedule five interviews.',
      contextType: 'company',
      contextName: 'Proairesis AI',
      parentId: null,
      workflowKey: 'startup_demo',
      workflowType: 'Customer validation',
      status: 'review',
      priority: 'normal',
      executorType: 'agent',
      accountableName: 'Jenny Men',
      waitingReason: 'Waiting for founder review',
      activationEvent: null,
      conditionText: '',
      sourceLabel: 'AI Startup goal',
      sourcePath: startupSource,
      startAt: null,
      dueAt: '2026-09-11T08:00:00.000Z',
      completedAt: null,
      updatedAt: '2026-09-09T09:35:00.000Z',
    },
  ],
  agentSessions: [
    {
      id: 'agent_task_system',
      taskId: 'task_agent_group',
      taskTitle: 'Pilot an Agent Group on real daily work',
      name: 'Codex · Work OS implementation',
      codexThreadId: 'current-task',
      status: 'working',
      summary: 'Building the task hierarchy, workflow rules and agent board.',
      nextAction: 'Review the working implementation when Codex finishes.',
      lastHeartbeatAt: '2026-09-09T09:45:00.000Z',
      startedAt: '2026-09-09T09:05:00.000Z',
      completedAt: null,
      updatedAt: '2026-09-09T09:45:00.000Z',
    },
    {
      id: 'agent_resume',
      taskId: 'task_canonical_resume',
      taskTitle: 'Finish canonical IT résumé',
      name: 'Codex · Résumé evidence pipeline',
      codexThreadId: 'resume-pipeline',
      status: 'waiting_for_founder',
      summary:
        'Evidence structure is ready; the canonical résumé needs a final choice.',
      nextAction:
        'Choose the primary résumé version and confirm target role lane.',
      lastHeartbeatAt: '2026-09-09T07:40:00.000Z',
      startedAt: '2026-09-08T23:00:00.000Z',
      completedAt: null,
      updatedAt: '2026-09-09T07:40:00.000Z',
    },
    {
      id: 'agent_startup',
      taskId: 'task_business_sot',
      taskTitle: 'Draft one-page Business Source of Truth',
      name: 'Codex · Customer evidence synthesis',
      codexThreadId: 'business-sot',
      status: 'review',
      summary:
        'Draft completed from desk evidence; interviews remain unverified.',
      nextAction: 'Review the segment choice and schedule five interviews.',
      lastHeartbeatAt: '2026-09-09T06:20:00.000Z',
      startedAt: '2026-09-09T05:40:00.000Z',
      completedAt: null,
      updatedAt: '2026-09-09T06:20:00.000Z',
    },
    {
      id: 'agent_job_discovery',
      taskId: 'task_next_role',
      taskTitle: 'Secure the next suitable IT role',
      name: 'Codex · Canberra job discovery',
      codexThreadId: 'canberra-job-discovery',
      status: 'queued',
      summary: 'Ready to assess a new batch of suitable roles.',
      nextAction: 'Start after the canonical résumé profile is approved.',
      lastHeartbeatAt: null,
      startedAt: null,
      completedAt: null,
      updatedAt: '2026-09-09T09:00:00.000Z',
    },
  ],
};
